"""Add physics_assessments table

Revision ID: 114ac64622ef
Revises: 22583e7cdf45
Create Date: 2026-09-17 09:40:09.636659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114ac64622ef'
down_revision: Union[str, Sequence[str], None] = '22583e7cdf45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physics_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('epoch_count', sa.Integer(), nullable=False),
    sa.Column('evidence_payload', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_id'], ['infrastructures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('physics_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physics_assessments_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_physics_assessments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_physics_assessments_infrastructure_id'), ['infrastructure_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physics_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physics_assessments_infrastructure_id'))
        batch_op.drop_index(batch_op.f('ix_physics_assessments_id'))
        batch_op.drop_index(batch_op.f('ix_physics_assessments_classification'))

    op.drop_table('physics_assessments')
    # ### end Alembic commands ###
