"""Initial STRATA domain tables

Revision ID: 22583e7cdf45
Revises: 
Create Date: 2026-09-16 22:50:57.487648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22583e7cdf45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('structure_type', sa.Enum('BRIDGE', 'DAM', 'RETAINING_WALL', 'OTHER', name='structuretype', native_enum=False, length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('infrastructures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infrastructures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_infrastructures_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_infrastructures_structure_type'), ['structure_type'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_id', sa.String(length=36), nullable=False),
    sa.Column('acquisition_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deformation_mm', sa.Float(), nullable=True),
    sa.Column('velocity_mm_per_year', sa.Float(), nullable=True),
    sa.Column('coherence', sa.Float(), nullable=True),
    sa.Column('phase_quality', sa.Float(), nullable=True),
    sa.Column('incidence_angle', sa.Float(), nullable=True),
    sa.Column('los_displacement_mm', sa.Float(), nullable=True),
    sa.Column('atmospheric_indicator', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_id'], ['infrastructures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_acquisition_timestamp'), ['acquisition_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_infrastructure_id'), ['infrastructure_id'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('ml_classification', sa.String(length=100), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('physics_classification', sa.String(length=100), nullable=True),
    sa.Column('physics_confidence', sa.Float(), nullable=True),
    sa.Column('consensus_confidence', sa.Float(), nullable=True),
    sa.Column('consensus_classification', sa.String(length=100), nullable=True),
    sa.Column('temporal_confidence', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('UNKNOWN', 'NOMINAL', 'WATCH', 'WARNING', 'CRITICAL', name='risklevel', native_enum=False, length=50), nullable=False),
    sa.Column('execution_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_risk_level'), ['risk_level'], unique=False)

    op.create_table('chronology_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_result_id', sa.String(length=36), nullable=False),
    sa.Column('record_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chronology_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chronology_records_analysis_result_id'), ['analysis_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chronology_records_current_hash'), ['current_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_chronology_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chronology_records_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chronology_records_record_index'), ['record_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chronology_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chronology_records_record_index'))
        batch_op.drop_index(batch_op.f('ix_chronology_records_observation_id'))
        batch_op.drop_index(batch_op.f('ix_chronology_records_id'))
        batch_op.drop_index(batch_op.f('ix_chronology_records_current_hash'))
        batch_op.drop_index(batch_op.f('ix_chronology_records_analysis_result_id'))

    op.drop_table('chronology_records')
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_risk_level'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_observation_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_id'))

    op.drop_table('analysis_results')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_infrastructure_id'))
        batch_op.drop_index(batch_op.f('ix_observations_id'))
        batch_op.drop_index(batch_op.f('ix_observations_acquisition_timestamp'))

    op.drop_table('observations')
    with op.batch_alter_table('infrastructures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infrastructures_structure_type'))
        batch_op.drop_index(batch_op.f('ix_infrastructures_name'))
        batch_op.drop_index(batch_op.f('ix_infrastructures_id'))

    op.drop_table('infrastructures')
    # ### end Alembic commands ###
