"""add_infrastructure_id_to_chronology_records

Revision ID: 2ee95efb0fdd
Revises: 114ac64622ef
Create Date: 2026-09-17 12:35:32.300344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee95efb0fdd'
down_revision: Union[str, Sequence[str], None] = '114ac64622ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chronology_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('infrastructure_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_chronology_records_infrastructure_id'), ['infrastructure_id'], unique=False)
        batch_op.create_foreign_key('fk_chronology_records_infrastructure_id', 'infrastructures', ['infrastructure_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chronology_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chronology_records_infrastructure_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chronology_records_infrastructure_id'))
        batch_op.drop_column('infrastructure_id')

    # ### end Alembic commands ###
