"""add_phase7_infrastructure_risk_characterization

Revision ID: 7e42d1c25812
Revises: 2ee95efb0fdd
Create Date: 2026-09-17 13:31:50.510195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e42d1c25812'
down_revision: Union[str, Sequence[str], None] = '2ee95efb0fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_characterizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('infrastructure_id', sa.String(length=36), nullable=False),
    sa.Column('observation_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observation_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('epoch_count', sa.Integer(), nullable=False),
    sa.Column('characterization_state', sa.Enum('INSUFFICIENT_EVIDENCE', 'BASELINE', 'ENVIRONMENTAL_PATTERN', 'MONITOR', 'ELEVATED_ATTENTION', 'HIGH_ATTENTION', name='riskcharacterizationstate', native_enum=False, length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prototype_risk_index', sa.Float(), nullable=True),
    sa.Column('evidence_components', sa.JSON(), nullable=False),
    sa.Column('supporting_factors', sa.JSON(), nullable=False),
    sa.Column('suppressing_factors', sa.JSON(), nullable=False),
    sa.Column('uncertainty_factors', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('version_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_id'], ['infrastructures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_characterizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_characterizations_characterization_state'), ['characterization_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_characterizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_characterizations_infrastructure_id'), ['infrastructure_id'], unique=False)

    with op.batch_alter_table('infrastructures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material', sa.Enum('CONCRETE', 'STEEL', 'MASONRY', 'EARTH', 'ROCK', 'COMPOSITE', 'UNKNOWN', name='materialtype', native_enum=False, length=50), nullable=False, server_default='UNKNOWN'))
        batch_op.add_column(sa.Column('criticality', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', 'UNKNOWN', name='criticalitylevel', native_enum=False, length=50), nullable=False, server_default='UNKNOWN'))
        batch_op.add_column(sa.Column('expected_behavior', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('geometry_context', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('critical_zones', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('historical_baseline', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('calibration_profile', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('profile_version', sa.String(length=50), nullable=False, server_default='v1.0.0'))
        batch_op.create_index(batch_op.f('ix_infrastructures_criticality'), ['criticality'], unique=False)
        batch_op.create_index(batch_op.f('ix_infrastructures_material'), ['material'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infrastructures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infrastructures_material'))
        batch_op.drop_index(batch_op.f('ix_infrastructures_criticality'))
        batch_op.drop_column('profile_version')
        batch_op.drop_column('calibration_profile')
        batch_op.drop_column('historical_baseline')
        batch_op.drop_column('critical_zones')
        batch_op.drop_column('geometry_context')
        batch_op.drop_column('expected_behavior')
        batch_op.drop_column('criticality')
        batch_op.drop_column('material')

    with op.batch_alter_table('risk_characterizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_characterizations_infrastructure_id'))
        batch_op.drop_index(batch_op.f('ix_risk_characterizations_id'))
        batch_op.drop_index(batch_op.f('ix_risk_characterizations_characterization_state'))

    op.drop_table('risk_characterizations')
    # ### end Alembic commands ###
