from datetime import datetime
from typing import Any, Dict, Optional
from pydantic import BaseModel, ConfigDict, Field
from backend.app.db.models import RiskLevel


class AnalysisResultRead(BaseModel):
    id: str
    observation_id: str
    ml_classification: Optional[str] = None
    ml_confidence: Optional[float] = None
    physics_classification: Optional[str] = None
    physics_confidence: Optional[float] = None
    consensus_confidence: Optional[float] = None
    consensus_classification: Optional[str] = None
    temporal_confidence: Optional[float] = None
    risk_level: RiskLevel
    execution_metadata: Optional[Dict[str, Any]] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class ChronologyRecordRead(BaseModel):
    id: str
    observation_id: str
    analysis_result_id: str
    record_index: int
    timestamp: datetime
    payload_hash: str
    previous_hash: str
    current_hash: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class AnalysisPipelineResponse(BaseModel):
    analysis_result: AnalysisResultRead
    is_development_stub: bool = Field(
        default=True,
        description="Indicates whether this result was generated by prototype development stubs rather than production models",
    )
    component_breakdown: Dict[str, Any] = Field(
        ...,
        description="Detailed diagnostic output from InSAR normalizer, ML stub, Physics stub, and Consensus stub",
    )
    chronology_record: Optional[ChronologyRecordRead] = Field(
        default=None,
        description="Tamper-evident SHA-256 evidence chronicle record",
    )
    scientific_integrity_notice: str = Field(
        default="STRATA Phase 1 Prototype: ML, physics, and consensus calculations are explicitly stubbed. No real structural failure or Sentinel-1 inference is asserted.",
        description="Mandatory scientific disclaimer",
    )
